version: "3"

services:
  xmrig:
    container_name: xmrig
    restart: unless-stopped

    build:
        context: ./src

    command:
        - "--config=/config.json"
        - "--donate-level=0"

    volumes:
       - ./config.json:/config.json:ro
       - /lib/modules:/lib/modules:ro

    privileged: true
    cap_add:
       - SYS_ADMIN
